# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b980201333a14a888797ca8eb584cfb4731c8f8c5e31af0c52ced19217f4a6bf8bcdf66eb9c7182782ef789673d37957bc999bf54a446820adda85711b70b163

test:
  secret_key_base: 34a1d14d1ad0d2f6b4e2f2601e5bb772925b939ee1c007bd0d15b7f7d03c7714f4dbdf517dfaa6a672835c54f4a91bddb5fe47ae162d8dcb2df3a4e8652faefe

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
